---
- name: Install helm charts
  helm:
    host: "{{ l_helm_host }}"
    port: "{{ l_helm_port }}"
    chart:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
      source:
        type: "{{ item.source.type }}"
        location: "{{ item.source.location }}"
        reference: "{{ item.source.reference | default(omit) }}"
        path: "{{ item.source.path | default(omit) }}"
    state: "{{ item.state }}"
    name: "{{ item.release }}"
    namespace: "{{ item.namespace }}"
    values: "{{ item['values'] }}"
  loop: "{{ helm_charts }}"
