---
- name: install required yum packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ helm_yum_packages }}"

- name: install required pip packages
  pip:
    name: "{{ item }}"
  loop: "{{ helm_pip_packages }}"
