---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: rke
    box: centos/7
    cpus: 1
    memory: 4096
    interfaces:
      - auto_config: true
        ip: 172.28.128.3
        network_name: private_network
        type: static
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      rke:
        rke_nodes:
          - address: 172.28.128.3
            user: vagrant
            role: [controlplane, etcd, worker]

        helm_charts:
          - name: nginx
            version: 0.1.0
            release: nginx-test
            namespace: default
            source:
              type: git
              location: https://github.com/helm/helm.git
              reference: master
              path: docs/examples/nginx
            state: present
            values: {}
          - name: memcached
            version: 0.4.0
            release: memcached-test
            namespace: default
            source:
              type: repo
              location: https://kubernetes-charts.storage.googleapis.com
            state: present
            values: {}

  lint:
    name: ansible-lint
    options:
      x: [
        "204"  # Lines should be no longer than 160 chars
      ]
verifier:
  name: testinfra
  lint:
    name: flake8
